import urllib.request
import json
import time

def test_api_start():
    url = "http://127.0.0.1:8000/api/classroom/start"
    payload = {
        "grade_selection": [{"grade": "3", "subject": "Math"}],
        "duration_minutes": 40,
        "resources": {
            "tablets": 2,
            "tv": True,
            "printer": True,
            "internet": True
        },
        "session_constraints": {}
    }
    
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    
    print("Sending POST request to http://127.0.0.1:8000/api/classroom/start ...")
    t0 = time.time()
    try:
        with urllib.request.urlopen(req) as resp:
            status = resp.status
            body = resp.read().decode("utf-8")
            elapsed = time.time() - t0
            print(f"HTTP Status: {status} (in {elapsed:.1f}s)")
            
            res_json = json.loads(body)
            print("\n--- API RESPONSE STRUCTURE ---")
            print("Session ID:", res_json.get("session_id"))
            print("Status:", res_json.get("status"))
            
            cycle_rec = res_json.get("cycle_record") or {}
            act_designs = cycle_rec.get("activity_designs") or {}
            del_acts = res_json.get("delivered_activities") or []
            
            print("\nGenerated Activity Designs Keys:", list(act_designs.keys()))
            print("Delivered Activities Count:", len(del_acts))
            
            if del_acts:
                first_act = del_acts[0]
                print("\n=== DELIVERED ACTIVITY GENERATED BY GROQ LLM ===")
                print("Activity ID:", first_act.get("activity_id"))
                print("Grade:", first_act.get("grade"))
                print("Subject:", first_act.get("subject"))
                print("Topic:", first_act.get("topic"))
                print("Activity Type:", first_act.get("activity_type"))
                print("Content Instructions:", first_act.get("content", {}).get("instructions"))
                print("Content Items:", first_act.get("content", {}).get("items"))
                
            shared_st = res_json.get("shared_state") or {}
            active_sess = shared_st.get("active_session") or {}
            print("\nShared State Active Session ID:", active_sess.get("session_id"))
            print("Shared State Cycle Record Present:", "cycle_record" in active_sess)
            
            # Verify HTTP 200 and presence of real LLM generated activity
            assert status == 200, f"Expected 200, got {status}"
            assert len(del_acts) > 0, "No delivered activities in API response!"
            assert "instructions" in del_acts[0].get("content", {}), "Activity content missing instructions!"
            
            print("\nSUCCESS! Single grade API start session validation passed completely!")
            
    except urllib.error.HTTPError as e:
        print(f"HTTP Error {e.code}: {e.read().decode('utf-8')}")
        raise

if __name__ == "__main__":
    test_api_start()
